// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApovpT7p-NvK-Kgxf43qvjozppljvyWEg',
    appId: '1:179185193081:web:0b906146fcc8e6b72704a8',
    messagingSenderId: '179185193081',
    projectId: 'therapal-e5287',
    authDomain: 'therapal-e5287.firebaseapp.com',
    storageBucket: 'therapal-e5287.firebasestorage.app',
    measurementId: 'G-86HQ1XFHS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ1OPnijQnFeVdWpglOJLIAFL3yiFQYA4',
    appId: '1:179185193081:android:f40a1afe4fabc8442704a8',
    messagingSenderId: '179185193081',
    projectId: 'therapal-e5287',
    storageBucket: 'therapal-e5287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-2j1bi5mChqbGLuX_mrVTwAR6alLNqw',
    appId: '1:179185193081:ios:c4e03e9c4d7191022704a8',
    messagingSenderId: '179185193081',
    projectId: 'therapal-e5287',
    storageBucket: 'therapal-e5287.firebasestorage.app',
    iosBundleId: 'com.example.therapal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-2j1bi5mChqbGLuX_mrVTwAR6alLNqw',
    appId: '1:179185193081:ios:c4e03e9c4d7191022704a8',
    messagingSenderId: '179185193081',
    projectId: 'therapal-e5287',
    storageBucket: 'therapal-e5287.firebasestorage.app',
    iosBundleId: 'com.example.therapal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApovpT7p-NvK-Kgxf43qvjozppljvyWEg',
    appId: '1:179185193081:web:721778f7b39ba29e2704a8',
    messagingSenderId: '179185193081',
    projectId: 'therapal-e5287',
    authDomain: 'therapal-e5287.firebaseapp.com',
    storageBucket: 'therapal-e5287.firebasestorage.app',
    measurementId: 'G-HMCQQRP94Y',
  );

}